### PR TITLE
Added a simple search bar

### LINKED ISSUE #8: Search Screen

### PR DESCRIPTION
**Pull request by kazimsayed954**
player_3aMpxQIBQA
player_F8oBvLrWlm

### CODE REVIEW

**Comment by kazimsayed954** [comment]
Could u link the search screen issue with this issue

**Comment by himanshusharma89** [comment]
@kazimsayed954 Only push the required file, search screen file, and pubspec.yaml if required.

**Comment by himanshusharma89** [comment]
@kazimsayed954 Update on the work

**Comment by himanshusharma89** [comment]
@kazimsayed954  Any update?

**Comment by kazimsayed954** [comment]
Yeah I will working on it I will create a PR soon!!

**Pull request closed without merging**
