### PR TITLE
Added email auth along with sign up, log in, create profile page.

### PR DESCRIPTION
**Pull request by rahulgambhir**
tradewinds_auth
tradewinds_database
email_auth

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@rahulgambhir Remove all the fonts files and use Google Fonts

**Comment by rahulgambhir** [comment]
@himanshusharma89 Done! Please check.

**Comment by himanshusharma89** [comment]
@rahulgambhir I'll not merge it, for now, we will have a video call soon and resolve many issues

**Comment by rahulgambhir** [comment]
Okay!

**Pull request merged**
